// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ACtestCpp
SEXP ACtestCpp(arma::mat z_e, arma::mat z, arma::mat e, int h, bool univariate, bool LM, bool HC0, bool HC1, bool HC2, bool HC3);
RcppExport SEXP VARtests_ACtestCpp(SEXP z_eSEXP, SEXP zSEXP, SEXP eSEXP, SEXP hSEXP, SEXP univariateSEXP, SEXP LMSEXP, SEXP HC0SEXP, SEXP HC1SEXP, SEXP HC2SEXP, SEXP HC3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type z_e(z_eSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type e(eSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    Rcpp::traits::input_parameter< bool >::type univariate(univariateSEXP);
    Rcpp::traits::input_parameter< bool >::type LM(LMSEXP);
    Rcpp::traits::input_parameter< bool >::type HC0(HC0SEXP);
    Rcpp::traits::input_parameter< bool >::type HC1(HC1SEXP);
    Rcpp::traits::input_parameter< bool >::type HC2(HC2SEXP);
    Rcpp::traits::input_parameter< bool >::type HC3(HC3SEXP);
    rcpp_result_gen = Rcpp::wrap(ACtestCpp(z_e, z, e, h, univariate, LM, HC0, HC1, HC2, HC3));
    return rcpp_result_gen;
END_RCPP
}
// computeET_LM
arma::mat computeET_LM(arma::mat resid, int h);
RcppExport SEXP VARtests_computeET_LM(SEXP residSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type resid(residSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(computeET_LM(resid, h));
    return rcpp_result_gen;
END_RCPP
}
// computeMARCH
double computeMARCH(arma::mat e, int h);
RcppExport SEXP VARtests_computeMARCH(SEXP eSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type e(eSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(computeMARCH(e, h));
    return rcpp_result_gen;
END_RCPP
}
// makeVar
arma::mat makeVar(arma::mat Ystart, arma::mat e, arma::mat param, int p, bool constFlag, bool trendFlag, bool exogenFlag, arma::mat exogen);
RcppExport SEXP VARtests_makeVar(SEXP YstartSEXP, SEXP eSEXP, SEXP paramSEXP, SEXP pSEXP, SEXP constFlagSEXP, SEXP trendFlagSEXP, SEXP exogenFlagSEXP, SEXP exogenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Ystart(YstartSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type e(eSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type param(paramSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type constFlag(constFlagSEXP);
    Rcpp::traits::input_parameter< bool >::type trendFlag(trendFlagSEXP);
    Rcpp::traits::input_parameter< bool >::type exogenFlag(exogenFlagSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type exogen(exogenSEXP);
    rcpp_result_gen = Rcpp::wrap(makeVar(Ystart, e, param, p, constFlag, trendFlag, exogenFlag, exogen));
    return rcpp_result_gen;
END_RCPP
}
