# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.ACtestCpp <- function(z_e, z, e, h, univariate, LM, HC0, HC1, HC2, HC3) {
    .Call(VARtests_ACtestCpp, z_e, z, e, h, univariate, LM, HC0, HC1, HC2, HC3)
}

computeET_LM <- function(resid, h) {
    .Call(VARtests_computeET_LM, resid, h)
}

computeMARCH <- function(e, h) {
    .Call(VARtests_computeMARCH, e, h)
}

.makeVar <- function(Ystart, e, param, p, constFlag, trendFlag, exogenFlag, exogen) {
    .Call(VARtests_makeVar, Ystart, e, param, p, constFlag, trendFlag, exogenFlag, exogen)
}

